spring:
 #server.port: 8080
  main:
    banner-mode: off
  application:
    name: spring-database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false